### ISSUE TITLE
allow for a different cni plugin directory?

### ISSUE THREAD

**Issue by 06kellyjac** [AkihiroSuda/nerdctl#23]
Can you add an override environment variable so the cni plugin directory can be somewhere different to `/opt/cni/bin`? Or is that a bad idea?

https://github.com/AkihiroSuda/nerdctl/blob/master/run.go#L169
https://github.com/containerd/go-cni/blob/master/types.go#L22

**Comment by AkihiroSuda** [comment]
SGTM
