### ISSUE TITLE
Support `nerdctl save [CONTAINER IMAGE ID]`

### ISSUE THREAD

**Issue by soharaki** [AkihiroSuda/nerdctl#33]
Support nerdctl save [CONTAINER IMAGE ID].

**Comment by soharaki** [comment]
@AkihiroSuda 
Hi, when I export a tarball directly using `client.Export` will output the OCI Image Spec tar instead of a Docker Image Spec v1.2 tar.

* Any `client.Export` options or alt-implementations which can export the Docker Image Spec v1.2?
* Should I explicitly explain that it is the OCI Image Spec tar in the help?

Any advices. Thank you.

* refs: 

```golang
func saveContainer(images []string, out io.Writer, saveOpts []archive.ExportOpt, clicontext *cli.Context) error {
	client, ctx, cancel, err := newClient(clicontext)
	if err != nil {
		return err
	}
	defer cancel()

	// Set the default platform
	saveOpts = append(saveOpts, archive.WithPlatform(platforms.Default()))

	is := client.ImageService()
	for _, img := range images {
		saveOpts = append(saveOpts, archive.WithImage(is, img))
	}

	return client.Export(ctx, out, saveOpts...)
}
```

**Comment by AkihiroSuda** [comment]
OCI Archive with manifest.json is compatible with Docker Image Spec
