### ISSUE TITLE
--entrypoint support for nerdctl run

### ISSUE THREAD

**Issue by shishir-a412ed** [AkihiroSuda/nerdctl#87]
Is there a plan to support `--entrypoint` for the `nerdctl run` command?
I see it's supported in `podman` so was wondering if it's part of the `nerdctl` roadmap?

I can take a stab at it, but right now I am not very clear on how to go about it! since [`OCI runtime spec`](https://github.com/opencontainers/runtime-spec/blob/master/schema/config-schema.json) doesn't have a notion of `entrypoint`

/cc @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Yes, on roadmap 👍
