### ISSUE TITLE
Support `nerdctl rm [SHORTID]`

### ISSUE THREAD

**Issue by AkihiroSuda** [AkihiroSuda/nerdctl#9]
Currently, `nerdctl rm 133fd7a617f4eb77db0ef395c66e652dc2a292048f34bf45a9a741c986a53f53` can't be shorten like `nerdctl rm 133fd7a617f4`

**Comment by knight42** [comment]
As for dockerd, such feature is implemented on the server side:
https://github.com/moby/moby/blob/eeddea2f9026b9b3e6a14b8bdb40bafec81ef10a/daemon/container.go#L31-L38

should we do this in containerd as well? Or make the client get the list of IDs first and find out the matched one?

**Comment by AkihiroSuda** [comment]
Client side
